/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  skill: [
    'skill/introduction',
    {
      label: 'Vue',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'skill/vue/Vue响应式数据之Object',
        'skill/vue/Vue响应式数据之Array',
        'skill/vue/Vue响应式数据之基本数据类型',
        'skill/vue/Vue-component',
        'skill/vue/Pinia',
      ],
    },
    {
      label: 'React',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/react',
        },
      ],
    },
    {
      label: 'Web',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/web',
        },
      ],
    },
    {
      label: 'JavaScript',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/js',
        },
      ],
    },
    {
      label: 'Node',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/node',
        },
      ],
    },
    {
      label: 'Css',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: ['skill/css/记Tailwind CSS使用', 'skill/css/有趣且实用的CSS小技巧'],
    },
    {
      label: 'Go',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'skill/go/Go环境安装',
        'skill/go/Go语言之json使用',
        'skill/go/Go发送http请求',
        'skill/go/Go调用js代码',
        'skill/go/Go并发',
        'skill/go/Gin框架初体验'
      ],
    },
    {
      label: '算法',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/algorithm',
        },
      ],
    },
    {
      label: '逆向',
      type: 'category',
      link: {
        title: '逆向笔记',
        description: 'Web逆向与安卓逆向笔记',
        type: 'generated-index',
        keywords: ['reverse', 'web', 'android', 'frida'],
      },
      items: [
        {
          label: '安卓',
          type: 'category',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/reverse/android',
            },
          ],
        },
        {
          label: 'Web',
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/reverse/web',
            },
          ],
        },
        {
          label: '密码学',
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/reverse/crypto',
            },
          ],
        },
      ],
    },
    {
      label: 'Docker',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/docker',
        },
      ],
    },
    {
      label: '数据库',
      type: 'category',
      link: {
        // title: '',
        // description: '',
        type: 'generated-index',
        keywords: ['database', 'mysql', 'mongodb', 'redis', 'elasticsearch'],
      },
      items: [
        {
          label: 'Mysql',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/mysql/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/mysql',
            },
          ],
        },
        {
          label: 'MongoDB',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/mongo/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/mongo',
            },
          ],
        },
        {
          label: 'Redis',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/redis/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/redis',
            },
          ],
        },
        {
          label: 'Elasticsearch',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/elasticsearch/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/elasticsearch',
            },
          ],
        },
      ],
    },
    {
      label: '杂项',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/other',
        },
      ],
    },
  ],
  tools: [
    'tools/introduction',
    'tools/Everything快速搜索本地文件',
    'tools/Windows Terminal美化',
    'tools/Windows自定义右键菜单',
    'tools/VScode相关配置',
    'tools/IDEA基本配置',
    'tools/Wappalyzer识别网站上的技术',
    'tools/Jetbrains系列产品激活方法',
  ]
}

module.exports = sidebars
