
module.exports = {
  /*   mySidebar: [
      {
        type: 'autogenerated',
        dirName: '.', // 从 docs 文件夹生成侧边栏切片 (或 versioned_docs/<版本>)
      },
    ], */

  skill: [ // skillSidebar
    "skill/skill-intro",
    {
      type: 'category',
      label: 'NodeJs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/nodejs',
        },
      ],
    },
    {
      type: 'category',
      label: '开发',
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/develop',
        },
      ],
    },
    {
      type: 'category',
      label: '数据库',
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/database',
        },
        /*         { MongoDB: [], },
                { Mysql: [], },
                { Redis: [], },
                { ElasticSearch: [], } */
      ],
    },
    {
      type: 'category',
      label: '逆向',
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/reverse',
        },
      ],
    },
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/js',
        },
      ],
    },
    {
      type: 'category',
      label: 'Python',
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/python',
        },
      ],
    },
    {
      type: 'category',
      label: 'Go',
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/go',
        },
      ],
    },
    /*     {
          type: 'category',
          label: '运维',
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/operation',
            },
          ],
        }, */
    {
      type: 'category',
      label: 'Web',
      items: [
        {
          CSS: [],
        }
      ],
    },
  ],
  recommend: [
    'recommend/recommend-intro',
    {
      type: 'category',
      label: '推荐',
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/recommend',
        },
      ],
    },
    // 'recommend/recommend-intro',
  ],
  essay: [
    {
      type: 'autogenerated',
      dirName: 'essay', // 从 docs 文件夹生成侧边栏切片 (或 versioned_docs/<版本>)
    },
  ],
  /*   tools: {
      简介: ["tools/tools-intro"],
      "CSS 工具": ["tools/glassmorphism-generator/glassmorphism-generator"],
    }, */
};
