/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
/*   mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 从 docs 文件夹生成侧边栏切片 (或 versioned_docs/<版本>)
    },
  ], */
  skill: [
    "skill/skill-intro",
    {
      JavaScript: [],
      CSS: [],
      数据库: [
        { MongoDB: [], },
        { Mysql: [], },
        { Redis: [], },
        { ElasticSearch: [], }
      ],
      浏览器: [
      ],
      Web: [
        // {
        //   特效: [],
        // }
      ],
      网络: [],
      Vue: [],
      逆向: [],
      NodeJs: [
        {
          Express: [],
        }
      ],
      TypeScript: [

      ],
      工具: [],
    }
  ],
  resources: [
    // "resources/resources-intro",
    {
      效率工具: [],
      "UI 设计": [],
    },
  ],
  recommend: [
    'recommend/recommend-intro',
    // 'recommend/recommend-intro',
  ],
  /*   tools: {
      简介: ["tools/tools-intro"],
      "CSS 工具": ["tools/glassmorphism-generator/glassmorphism-generator"],
    }, */
};
